name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-java@v2
        with:
            distribution: 'zulu'
            java-version: '11'
            java-package: jdk
          
      - name: Test with Android Emulator Runner
        uses: ReactiveCircus/android-emulator-runner@v2.14.3
        with: 
            api-level: 29
            script: ./gradlew connectedCheck jacocoTestReport

      - name: Generate report
        uses: actions/upload-artifact@v2
        with:
          name: report 
          path: app/build/reports/jacoco/jacocoTestReport

      - name: Download Test Report Folder
        uses: actions/download-artifact@v2
        with:
          name: report
          path: app/build/reports/jacoco/jacocoTestReport

      - name: Upload Test Report
        uses: codecov/codecov-action@v3
        with:
          files: "app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml"
